# 该镜像需要依赖的基础镜像
FROM java:8
# 设置环境变量
ENV TZ=Asia/Shanghai
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 运行过程中创建一个mall-tiny-docker-file.jar文件
RUN bash -c 'touch /angular-springboot-rest-jwt.jar'
# ADD arthas-boot.jar /arthas-boot.jar
ENTRYPOINT java  -Xms512m   -Xmx1024m  -Xmn256m   -Xss256k   -XX:SurvivorRatio=8  -jar  /usr/share/myservice/myservice.jar
EXPOSE 8088


